### ISSUE TITLE
ANF and SNB not work

### ISSUE THREAD

**Issue by dl1gzw** [g0orx/linhpsdr#111]
Hello, since year 2020 Im using LinHPSDR. Its a great Software! Thanks. Here running the Built Date 2020-02-02. But in all follows Builts doesnt work ANF and SNB. Did have anyone a Idea why?
The Hardware here is a Stemlab Red Pitaya 14bit. OS is Linux Mint Cinnamon 20.2
Remarks: Today I have load the newst Build but is the same. :-(
My regards 
Hans DL1GZW

**Comment by g0orx** [comment]
I have fixed the problem with ANF and SNB not setting/resetting.
-- John
