### ISSUE TITLE
OS/X Support

### ISSUE THREAD

**Issue by jancona** [g0orx/linhpsdr#14]
I know the project is named **lin**hpsdr, but I was able to get it running on OS/X Sierra without too much effort. I have my [PiSDR](https://www.pi-sdr.net/pi-sdr/)/[RS-HFIQ](https://www.hobbypcb.com/rs-hfiq) running just fine. (It's recognized as a Hermes-Lite.) Let me know if you would be interested in a PR. If so, I can clean up my changes and make one. Otherwise, feel free to close this issue.

Jim N1ADJ

**Comment by g0orx** [comment]
Hi Jim,
I would be interested in the changes for OS/X.   I have not done a lot of development recently due to ill health and some remodeling of our house.  I hope to get back to it soon.
-- John

**Comment by jancona** [comment]
Sounds good. I'll try to pull together a PR in the next few days. The biggest problem I had was that the Homebrew PulseAudio package is compiled without glib support. I'll probably have to figure out how to package my Homebrew formula changes.

I hope you feel better!
