### ISSUE TITLE
no sound - Ubuntu 16.04

### ISSUE THREAD

**Issue by satfan52** [g0orx/linhpsdr#22]
Hello,

I was hoping to make the application work on Ubuntu 16.04 as I have not yet switched to 17.04.
I have done all the compilations without issues and the application starts ok. I see the waterfall etc...
However I have no sound, the linHPSDR app does not even appear as a client application in the PulseAudio app list. I tried to find the settings in the application to force the use of PulseAudio, but I could not find it. 

Regards
Peter

**Comment by sq8mvy** [comment]
Hello,

LinHpsdr works fine with PulseAudio.
Go to Configure -> RX-0
At the bottom, select the sound card from the drop-down menu and then select Local Audio.
![linhpsdr_audio](https://user-images.githubusercontent.com/42500968/50046611-18abe380-00a6-11e9-843c-1e4fe27ebca8.png)


Regards
Pawel SQ8MVY

**Comment by satfan52** [comment]
Thanks Pawel!

Yes all ok, I found the settings. Everything works fine. 
Will try soon the ALEX interface 
Regards
Peter
