### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by larryw8er** [g0orx/linhpsdr#24]
With changes yesterday, install instructions fail:

larry@BigBlue:~/wdsp/linhpsdr$ make
rm -f version.o
gcc -g -Wno-deprecated-declarations -D GIT_DATE='"2019-02-03"' -D GIT_VERSION='"Beta"'  -O3 `pkg-config --cflags gtk+-3.0` -c -o audio.o audio.c
audio.c:36:10: fatal error: SoapySDR/Device.h: No such file or directory
 #include <SoapySDR/Device.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:205: recipe for target 'audio.o' failed
make: *** [audio.o] Error 1
larry@BigBlue:~/wdsp/linhpsdr$

**Comment by g0orx** [comment]
Fixed SoapySDR/Device.h includes when SOAPYSDR not defined
