### ISSUE TITLE
Support for Radioberry (pihpsdr)

### ISSUE THREAD

**Issue by imoldovavan** [g0orx/linhpsdr#26]
It would be great if linhpsdr would have an rx-gain slider like the pihpsdr, so that we can use it with Radioberry over the network. I am willing to help code this in if it is possible or maybe you can point me in the right direction. 
Thank you,  Ion  KC8CDQ.

**Comment by g0orx** [comment]
As long as the Radioberry identifies itself as a Hermes Lite then the Radio tab in linHPSDR configuration should have a gain slider for it. I will bring up my Radioberry and check.

**Comment by imoldovavan** [comment]
I used the release version. I will compile the latest code from master. I think that is the problem. I will let you know.

**Comment by imoldovavan** [comment]
Just recompiled and it is doing the same thing. The radio is being recognized as Hermes Lite, FPGA firmware version 4.0.  Under the Radio Tab it shows ADC-0  LNA Gain, which I can adjust from -12 to 40.  Shouldn't LNA_Gain be RX_Gain??

**Comment by g0orx** [comment]
Both the Radioberry and the Hermes Lite have a Low Noise Amplifier which this is controlling the gain of, hence the name LNA Gain.

**Comment by imoldovavan** [comment]
Can you confirm the behavior with the Radioberry? I am unable to lower the gain to usable levels. It works fine with the pihpsdr from PA3GSB on the pi itself, but not thru network.

**Comment by imoldovavan** [comment]
fixed in https://github.com/g0orx/linhpsdr/commit/2bbccc27504118966358d69702d7fd14d38e3311 commit.
"I have changed the code to check for greater than 4.0 firmware version. Radioberry currently returns 4.0 but only handles the old way of setting the LNA gain. g0orx"
