### ISSUE TITLE
Tx power out down on pihpsdr power

### ISSUE THREAD

**Issue by radi8** [g0orx/linhpsdr#27]
The power out on my Hermes-lite 2 is down around 3db compared to the power out I get from pihpsdr and quisk. This is the case for both tune and mox. I have the Apollo filter selected as this signal is used to switch on the 5 watt PA for the HL2. Hope that this is something obvious.

73, Graeme ZL2APV

**Comment by g0orx** [comment]
I do not have a Hermes-lite to test with but will take a look to see if I can see anything.

-- John

**Comment by radi8** [comment]
Thanks John, I should have checked with the HL2 group to make sure that the
others have the same problem and will do. We need to get something written
to get HL2 soapy compatible and I guess that you are concentrating on soapy
remote as a client/server/server.

**Comment by radi8** [comment]
I have confirmation from another HL2 user that the output power is about 3 dB down using linhpsdr compared to other radios. He was using the Apollo filter selection to activate the HL2 PA, full slider for power out and 38.8 on the tested bands. This is the same as I was using.

73, Graeme ZL2APV

**Comment by radi8** [comment]
Not sure where you did the fix John but I get full power now - Thank you.
