### ISSUE TITLE
ANAN-10E issues

### ISSUE THREAD

**Issue by k1yw** [g0orx/linhpsdr#3]
During discovery - appears as "Hermes"

**Comment by g0orx** [comment]
The firmware returns a device type as part of discovery which in the case if the ANAN-10E is Hermes as it is a Hermes class board that is in the radio. The model of the radio has to be manually set in the configuration dialog.

**Comment by k1yw** [comment]
John,

Ok, understood. Just trying to help if I can.  I will continue my testing...

Greg
