### ISSUE TITLE
Pi SDR IQ (Hermes Lite)

### ISSUE THREAD

**Issue by csylvain** [g0orx/linhpsdr#30]
sometime between git date "Build: 2018-12-02 Beta" (obtained at https://github.com/N5FPP/linhpsdr.git ) and git date "Build: 2019-02-04 Beta" (obtained from this repo), the receiver panel broke (no audio, no waterfall, no nothing) [when not discovered as "In Use", obviously].

i note the the logs are similar except following changes in the console log:
(was) "starting Linux HPSDR (Beta): Hermes Lite P1 v25.5"
(now) "starting Linux HPSDR (Beta): Hermes Lite P2 v25.5"
and
(was) "protocol1: receive_thread"
(now) "ERROR: protocol1: receiver_thread: recvfrom socket failed: Radio not sending data"

with Wireshark, i could see the incoming UDP stream which looks very much like the UDP stream to pihpsdr or PowerSDR (both of those on separate machines from the linhpsdr host).

**Comment by g0orx** [comment]
Fixed. Problem was the addition of a timeout on receiving data in the firmware that was hit after starting the radio but before the software had finished initializing.
