### ISSUE TITLE
Radioberry testing of beta 4-23-19

### ISSUE THREAD

**Issue by imoldovavan** [g0orx/linhpsdr#32]
Here is the video of testing the latest beta on my majaro system. 
https://youtu.be/St0QobSouHA
The gain seems too high. On the windows machine running powersdr mrx everything works good and I don't see any of those peaks that look like AM stations bleeding over from the broadcast band. Let me know if I you want me to perform other tests.
Thank you,
Ion
KC8CDQ

**Comment by g0orx** [comment]
OK, I will have to wait to test with a real Hermes Lite 2 rather than the RadioBerry.  With the RadioBerry the display looks like this monitoring 14.074 FT8.  I will try to get access to a Hermes Lite 2 in the next few days.

![hermeslite2](https://user-images.githubusercontent.com/1197045/56646875-57673100-6678-11e9-9042-aa7a86a96e5c.png)

**Comment by g0orx** [comment]
FYI - this is what I have been working mostly on recently. QO-100 (Es'hail 2) support with RTLSDR and LimeSDR.

![qo-100](https://user-images.githubusercontent.com/1197045/56648265-e8d7a280-667a-11e9-9d7f-54891de18737.png)

**Comment by imoldovavan** [comment]
Hi John. 
I have been playing with the rb and found a sweet spot on the gain value. I have another video showing the efect the gain value has on the receive. 
https://youtu.be/Sd4kCAkCg58
Jumping from 19 to 20 wipes out the receive. Going down in value the "AM" peaks start to show up. Not sure if this is normal behavior, but I hope this helps in some way.
Thank you.

**Comment by g0orx** [comment]
I have contacted Johan as it looks like there may be a bug with the Radioberry code implementing the LNA gain settings when the firmware/gateware version is >=4.0.  I noticed that in hermeslite.c it is only taking the low 5 bits for the attenuation rather than the 6 bits.  It seems we have 2 separate problems one using the Radioberry hardware and one using the Hermes Lite 2 hardware.

I will be testing with both later today.

-- John

**Comment by g0orx** [comment]
I have changed the code to check for greater than 4.0 firmware version.  Radioberry currently returns 4.0 but only handles the old way of setting the LNA gain.

**Comment by imoldovavan** [comment]
I believe the receive was cleaner before. I can see the "AM" peaks now, and I can't make them go away.
https://youtu.be/qGGnbg138oE

**Comment by g0orx** [comment]
I can see that the gian level is moving up and down evenly on your 
video.  I just suspect you have too much gain from the antenna. Do you 
have any filtering between the antenna and the Radioberry?

-- John

**Comment by imoldovavan** [comment]
The 'AM' peaks are not visible on the windows machine running PowerSDR MRx and the "Hermes Step Attenuator" setting at 12.  I will try to do a video side by side.

**Comment by g0orx** [comment]
I will check if there is another gain setting that is enabled on it. I have
no problems with mine so may be hard to debug.

-- John

**Comment by imoldovavan** [comment]
This is more prevalent on 40 and 80 meters bands, towards the end of the day when the AM stations start booming in.

**Comment by imoldovavan** [comment]
Here are two videos recorded within 5 minutes of each other showin the 40 meters band on linhpsdr and powersdr Mrx. there is no trace of "am" signals on the powersdr mrx program.
https://youtu.be/jOJDvnNxOJk
https://youtu.be/pRUbvFGXxD0
Hope this helps.
Thank you,
Ion
KC8CDQ

**Comment by g0orx** [comment]
Is this with the latest update I pushed yesterday?

-- John

**Comment by g0orx** [comment]
I can see it is not with the latest push. Can you try that version. You may
need to delete the props file for the radio in ~/. local/share/linhpsdr.

-- John

**Comment by imoldovavan** [comment]
Hi John,
I deleted the two props files, before firing up the program. I believe it need more attenuation. It behaves the same. The "AM" peaks are still visible. I also checked the bands with the Powersdr mrx and it works OK with that one. Here is the video.
https://youtu.be/vANHeeeVMHA
