### ISSUE TITLE
Build instructions for OS X no longer correct

### ISSUE THREAD

**Issue by sanamon** [g0orx/linhpsdr#36]
Hi,

It seems homebrew no longer supports the --with-glib option to install pulseaudio.
I asked on the homebrew list and got this answer from Sean Molenaar:

"All options have been removed from homebrew-core, which includes this one. If you need pulseaudio with glib you’ll have to maintain your own version."

This means that the build instructions in MacOS.md no longer works. 

Best Regards, Jonas

**Comment by g0orx** [comment]
I have removed pulsaudio requirement from MacOS.md as this never worked correctly because it would not provide a list of devices on the Mac. Have changed to use soundio on the Mac.

-- John

**Comment by sanamon** [comment]
Thanks John!

There might be something more that needs fixing in the OS X build
instructions?  Or something I messed up?

JonasS-MacBook-Pro:linhpsdr sanamon$ make -f Makefile.mac

rm -f version.o

gcc -Wno-deprecated-declarations -D GIT_DATE='"2019-05-07"' -D
GIT_VERSION='"Beta"'  -O3 -g `pkg-config --cflags gtk+-3.0`  -c -o main.o
main.c

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

Package 'libffi', required by 'gobject-2.0', not found

*main.c:20:10: **fatal error: **'gtk/gtk.h' file not found*

#include <gtk/gtk.h>

*         ^~~~~~~~~~~*

1 error generated.

make: *** [main.o] Error 1

JonasS-MacBook-Pro:linhpsdr sanamon$

I have installed

  brew install fftw
  brew install gtk+3
  brew install gnome-icon-theme
  brew install libsoundio

 and WDSP as per the instructions.

Best Regards,
Jonas

Den tis 7 maj 2019 kl 10:44 skrev John Melton <notifications@github.com>:

**Comment by g0orx** [comment]
I have added "brew install libffi" to MacOS.md
-- John

**Comment by sanamon** [comment]
Thanks John,

However, it does not seem to help (actually I already had tried installing
that)

JonasS-MacBook-Pro:linhpsdr sanamon$ brew install libffi

Warning: libffi 3.2.1 is already installed and up-to-date

To reinstall 3.2.1, run `brew reinstall libffi`

JonasS-MacBook-Pro:linhpsdr sanamon$ brew reinstall libffi

==> *Reinstalling **libffi*

==> *Downloading
https://homebrew.bintray.com/bottles/libffi-3.2.1.mojave.bottl
<https://homebrew.bintray.com/bottles/libffi-3.2.1.mojave.bottl>*

Already downloaded:
/Users/sanamon/Library/Caches/Homebrew/downloads/89b4ef328be250153e7a2b39982ac446e0b3bbfe7f3e2708912ba1976862c302--libffi-3.2.1.mojave.bottle.tar.gz

==> *Pouring libffi-3.2.1.mojave.bottle.tar.gz*

==> *Caveats*

libffi is keg-only, which means it was not symlinked into /usr/local,

because some formulae require a newer version of libffi.


For compilers to find libffi you may need to set:

  export LDFLAGS="-L/usr/local/opt/libffi/lib"


For pkg-config to find libffi you may need to set:

  export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"


==> *Summary*

🍺  /usr/local/Cellar/libffi/3.2.1: 16 files, 296.8KB

JonasS-MacBook-Pro:linhpsdr sanamon$ make clean

rm -f *.o

rm -f linhpsdr

JonasS-MacBook-Pro:linhpsdr sanamon$ make -f Makefile.mac

rm -f version.o

gcc -Wno-deprecated-declarations -D GIT_DATE='"2019-05-07"' -D
GIT_VERSION='"Beta"'  -O3 -g `pkg-config --cflags gtk+-3.0`  -c -o main.o
main.c

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

Package 'libffi', required by 'gobject-2.0', not found

*main.c:20:10: **fatal error: **'gtk/gtk.h' file not found*

#include <gtk/gtk.h>

*         ^~~~~~~~~~~*

1 error generated.

make: *** [main.o] Error 1

JonasS-MacBook-Pro:linhpsdr sanamon$

I might be able to get around that issue, by following the advise to
explicitly point to directory with libffi.pc using the PKG_CONFIG_PATH
variable?
I'm more concerned about the gtk.h not found error

Thanks again for Your efforts!
Best Regards,
Jonas


Den tis 7 maj 2019 kl 11:26 skrev John Melton <notifications@github.com>:

**Comment by sanamon** [comment]
Hi again,

Update :-)

Doing this seemed to solve both issues:

PKG_CONFIG_PATH="/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/" make -f
Makefile.mac

Best Regards,
Jonas

Den tis 7 maj 2019 kl 11:32 skrev Jonas Sanamon <jonas.sanamon@connective.nu
