### ISSUE TITLE
Violation of memory protection after switching to the TX tab in the configuration

### ISSUE THREAD

**Issue by sq8mvy** [g0orx/linhpsdr#61]
Probably after commit "Fix receiver_dialog settings change", switching to the "TX" tab violates memory protection. I didn't see this problem before this change.

Log:
switch_page: 1 OC
switch_page: 2 XVTR
switch_page: 3 RX-0
Output device changed: 2: alsa_output.pci-0000_00_1b.0.analog-stereo (Wbudowany dźwięk Analogowe stereo)
audio_open_output: PULSEAUDIO: alsa_output.pci-0000_00_1b.0.analog-stereo
audio_open_output: allocated local_audio_buffer 0x63a4810 size 16384 bytes
switch_page: 4 TX
transmitter: update_transmitter_audio_choices: tx=8
adding: Monitor of Wbudowany dźwięk Analogowe stereo
adding: Wbudowany dźwięk Analogowe stereo
adding: Monitor of Wbudowany dźwięk Digital Stereo (HDMI 3)
adding: Monitor of Wbudowany dźwięk Analogowe stereo
adding: Wbudowany dźwięk Analogowe stereo
adding: Monitor of Wbudowany dźwięk Digital Stereo (HDMI 3)
Input device changed: 0: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor (Wbudowany dźwięk Analogowe stereo)
mic_read_thread: ENTRY
switch_page: 5 Pure Signal
switch_page: 6 PA
switch_page: 3 RX-0
switch_page: 4 TX
transmitter: update_transmitter_audio_choices: tx=8
Close audio input
mic_read_thread: EXIT
Naruszenie ochrony pamięci
pawel@pawel-desktop:~$

**Comment by g0orx** [comment]
Source code fix now pushed.
