### ISSUE TITLE
Third receiver not working with redpitaya

### ISSUE THREAD

**Issue by satfan52** [g0orx/linhpsdr#69]
Hello,

I have tried to open 3 receivers with my redpitaya (Hermes)
Two receivers worked fine, the third one opened but did not work as expected
As you can see in the picture below, the spectrum on the 10m band (3rd receiver) is a replication of the spectrum of the 40m band (receiver 1 and assigned TX)

![linhpsdr- redpitaya-3 receivers open](https://user-images.githubusercontent.com/14941529/82526428-4cf5c000-9b34-11ea-998b-c730cced4a9d.png)

**Comment by g0orx** [comment]
I have not been able to reproduce this with my Hermes Lite 2, ANAN-100D or ANAN-8000DLE. Unfortunately I do not have a RedPitaya to test with.

Looking at this web page http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-hpsdr/

"This SDR transceiver consists of four digital down-converters (DDC) and one digital up-converter (DUC). The first two digital down-converters are connected to two ADC channels. Two additional digital down-converters are required for the amplifier linearization system. One of them is connected to the second ADC channel and the other one is connected to the output of the digital up-converter."

So it looks like there are only 2 DDC channels available for general use and the 2 extra channels are specific for Pure Signal only.

**Comment by satfan52** [comment]
There are actually 3 configurable receivers over 2 physical sma ports. But the the third receiver is actually dedicated to predistorsion and therefore operates on the same frequency band than the first one that controls the TX frequency, so there is indeed only two usable receivers. Sorry for the confusion.
