### ISSUE TITLE
[Feature Request] Remember band settings for frequency and display.

### ISSUE THREAD

**Issue by scap1784** [g0orx/linhpsdr#76]
Hello,

It would be really great if linhpsdr could remember band settings. For example if I want to flip over to 40 to see what it is like and then switch back to 20 meters I should end up at the same frequency that I was at before. Additionally I set the waterfall and panadapter a little different on each band (I perfer to do this manually and not rely on the automatic mode). It would be nice if these settings were tied to the band mode so that when I flipped to 40 which has a higher noise floor I didn't have to readjust all the settings. 

Thanks for the linux software its a godsend. Stay safe.

**Comment by g0orx** [comment]
I agree and it is on the TODO list.  The big question is should this be for each receiver or for the radio.  If I have one receiver on 20M and another on 40M. I then change the band on the first one from 20M to 15M, so the 20M setting is saved.  I then change the second receiver from 40M to 20M. Does it get the saved frequency from the first receiver or does it have it's own set of band frequencies?

**Comment by g0orx** [comment]
I have pushed the code to save/restore the frequency, mode, and filter and also the panadapter high, low, step and the waterfall high, low and automatic.

**Comment by scap1784** [comment]
This is amazing... Can't believe you added this so quickly. I am testing it out now but it looks good on first play. I only have one antenna hooked up so I can't talk about how it works when switching between antennas. I have more than one antenna but I haven't got them all run to the shack yet. I would think that the settings should be per antenna per band as different antennas will have different noise floors. Anyways I am really enjoying this software and it is the reason I bought the hermes-lite 2 to play with some more. Better watch out or I may be buying a anan-7000dle before long.
