### ISSUE TITLE
subrx no audio

### ISSUE THREAD

**Issue by scap1784** [g0orx/linhpsdr#79]
After the recent changes (the last 3 commits) I no longer get audio from the subrx when selected. The mainrx switches to the left ear but nothing but a red line shows up on the panadapter and no audio to the right ear.

**Comment by g0orx** [comment]
The subrx is something we are experimenting with. The single red line is
when the VFO B mode is CWL or CWU and is being tested for a way to quickly
qsy.  Try setting up VFO A to the mode and filter you want and then do a
transfer A>B and it should now show the red line and a cursor.

I think the answer is going to be to always use the mode and filter
settings of VFO A and only have VFO B have the frequency setting.

-- John
