### ISSUE TITLE
HL2 never switches to run. 

### ISSUE THREAD

**Issue by scap1784** [g0orx/linhpsdr#80]
I just got a HL2 and I am trying to use it with the software. I can see it and I tell linhpsdr to start the radio but the radio stays in idle and I get black panadapters. I can open another linhpsdr and I see the Hermes Lite V2 in Idle and I can still connect to it. This is on master.

**Comment by g0orx** [comment]
I cannot reproduce this with my HL2 and have not heard this from other users with HL2.  I suspect there is either a network problem or a timing problem.  Would it be possible to get a Wireshark trace to see the network traffic between the computer and the radio?

**Comment by g0orx** [comment]
I have quickly made a video of linhpsdr starting up on my system.  This is the same as the current master apart from some partial changes to the sliders on the main window. https://drive.google.com/file/d/1z5lvLdavORPeAkZ_cXQvK9Cqck-C1ZdP/view?usp=sharing

**Comment by scap1784** [comment]
I just got this today so I am working on getting it set up. I did a firmware update and it didn't connect the first time but I tried again and it has started working. I will watch your video and keep experimenting. Thanks for the quick response as always.
